// <auto-generated />
using System;
using CoopGameServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoopGameServer.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260819174654_CompleteMatchQueueTickets")]
    partial class CompleteMatchQueueTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoopGameServer.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("login_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("LoginId")
                        .IsUnique()
                        .HasDatabaseName("IX_accounts_login_id");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_accounts_player_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CoopGameServer.Domain.Inventories.InventoryItem", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlayerId", "ItemId");

                    b.ToTable("inventories", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventories_item_id_positive", "item_id > 0");

                            t.HasCheckConstraint("CK_inventories_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nickname");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("CoopGameServer.Domain.Rewards.RewardAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_audit_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GoldAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_amount");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int?>("ItemQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("item_quantity");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("reward_audits", null, t =>
                        {
                            t.HasCheckConstraint("CK_reward_audits_gold_nonnegative", "gold_amount >= 0");

                            t.HasCheckConstraint("CK_reward_audits_has_reward", "gold_amount > 0 OR item_id IS NOT NULL");

                            t.HasCheckConstraint("CK_reward_audits_item_reward_shape", "(item_id IS NULL AND item_quantity IS NULL) OR (item_id IS NOT NULL AND item_quantity IS NOT NULL AND item_id > 0 AND item_quantity > 0)");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Domain.Wallets.PlayerWallet", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlayerId");

                    b.ToTable("player_wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_player_wallets_gold_nonnegative", "gold >= 0");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Persistence.GameRooms.GameRoomRecord", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle");

                    b.PrimitiveCollection<Guid[]>("PartyIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("party_ids");

                    b.PrimitiveCollection<Guid[]>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("player_ids");

                    b.Property<string>("QueueKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("queue_key");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("RoomId");

                    b.HasIndex("QueueKey", "Lifecycle", "CreatedAt")
                        .HasDatabaseName("IX_game_rooms_queue_key_lifecycle_created_at");

                    b.ToTable("game_rooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_rooms_four_players", "cardinality(player_ids) = 4");

                            t.HasCheckConstraint("CK_game_rooms_lifecycle", "lifecycle IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_game_rooms_lifecycle_times", "(lifecycle = 0 AND started_at IS NULL AND completed_at IS NULL) OR (lifecycle = 1 AND started_at IS NOT NULL AND completed_at IS NULL) OR (lifecycle = 2 AND started_at IS NOT NULL AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("CK_game_rooms_party_count", "cardinality(party_ids) <= 4");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Persistence.GameRooms.GameRoomRequestRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("command_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload_json");

                    b.Property<string>("ResultPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_payload_json");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("RequestId");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("IX_game_room_requests_room_id");

                    b.ToTable("game_room_requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_room_requests_payload_shape", "(command_kind = 'Create' AND request_payload_json IS NOT NULL) OR (command_kind IN ('Start', 'Complete') AND request_payload_json IS NULL)");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Persistence.Matchmaking.MatchQueueMemberRecord", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("MemberOrder")
                        .HasColumnType("integer")
                        .HasColumnName("member_order");

                    b.HasKey("TicketId", "PlayerId");

                    b.HasIndex("TicketId", "MemberOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_match_queue_members_ticket_id_member_order");

                    b.ToTable("match_queue_members", null, t =>
                        {
                            t.HasCheckConstraint("CK_match_queue_members_order_nonnegative", "member_order >= 0");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Persistence.Matchmaking.MatchQueueRequestRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("command_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("QueueKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("queue_key");

                    b.Property<string>("RequestPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload_json");

                    b.Property<string>("ResultPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_payload_json");

                    b.HasKey("RequestId");

                    b.HasIndex("QueueKey")
                        .HasDatabaseName("IX_match_queue_requests_queue_key");

                    b.ToTable("match_queue_requests", (string)null);
                });

            modelBuilder.Entity("CoopGameServer.Persistence.Matchmaking.MatchQueueTicketRecord", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at");

                    b.Property<int>("EntryKind")
                        .HasColumnType("integer")
                        .HasColumnName("entry_kind");

                    b.Property<Guid>("LeaderPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("leader_player_id");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("QueueKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("queue_key");

                    b.Property<long>("QueueOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("queue_order");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("TicketId");

                    b.HasIndex("QueueKey", "PartyId")
                        .HasDatabaseName("IX_match_queue_tickets_queue_key_party_id");

                    b.HasIndex("QueueKey", "QueueOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_match_queue_tickets_queue_key_queue_order");

                    b.HasIndex("QueueKey", "Status", "QueueOrder")
                        .HasDatabaseName("IX_match_queue_tickets_queue_key_status_queue_order");

                    b.ToTable("match_queue_tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_match_queue_tickets_entry_kind", "entry_kind IN (0, 1)");

                            t.HasCheckConstraint("CK_match_queue_tickets_entry_shape", "(entry_kind = 0 AND party_id IS NOT NULL) OR (entry_kind = 1 AND party_id IS NULL)");

                            t.HasCheckConstraint("CK_match_queue_tickets_queue_order_positive", "queue_order > 0");

                            t.HasCheckConstraint("CK_match_queue_tickets_status", "status IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Persistence.Parties.PartyMemberRecord", b =>
                {
                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("JoinOrder")
                        .HasColumnType("integer")
                        .HasColumnName("join_order");

                    b.HasKey("PartyId", "PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_party_members_player_id");

                    b.HasIndex("PartyId", "JoinOrder")
                        .HasDatabaseName("IX_party_members_party_id_join_order");

                    b.ToTable("party_members", null, t =>
                        {
                            t.HasCheckConstraint("CK_party_members_join_order_nonnegative", "join_order >= 0");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Persistence.Parties.PartyRecord", b =>
                {
                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_room_id");

                    b.Property<Guid?>("LeaderPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("leader_player_id");

                    b.Property<int>("Lifecycle")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PartyId");

                    b.ToTable("parties", null, t =>
                        {
                            t.HasCheckConstraint("CK_parties_lifecycle", "lifecycle IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_parties_state_shape", "(lifecycle = 1 AND leader_player_id IS NULL AND current_room_id IS NULL) OR (lifecycle IN (0, 2) AND leader_player_id IS NOT NULL AND current_room_id IS NULL) OR (lifecycle = 3 AND leader_player_id IS NOT NULL AND current_room_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Persistence.Parties.PartyRequestRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("command_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid?>("ResultCurrentRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_current_room_id");

                    b.Property<int>("ResultError")
                        .HasColumnType("integer")
                        .HasColumnName("result_error");

                    b.Property<Guid?>("ResultLeaderPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_leader_player_id");

                    b.Property<int?>("ResultLifecycle")
                        .HasColumnType("integer")
                        .HasColumnName("result_lifecycle");

                    b.PrimitiveCollection<Guid[]>("ResultMemberPlayerIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("result_member_player_ids");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("RequestId");

                    b.HasIndex("PartyId")
                        .HasDatabaseName("IX_party_requests_party_id");

                    b.ToTable("party_requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_party_requests_command_subject", "(command_kind IN ('StartGame', 'CompleteGame') AND player_id IS NULL AND room_id IS NOT NULL) OR (command_kind IN ('Create', 'Join', 'Leave', 'Disband', 'QueueForMatch', 'CancelMatchQueue') AND player_id IS NOT NULL AND room_id IS NULL)");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Domain.Accounts.Account", b =>
                {
                    b.HasOne("CoopGameServer.Domain.Players.Player", null)
                        .WithOne()
                        .HasForeignKey("CoopGameServer.Domain.Accounts.Account", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoopGameServer.Domain.Inventories.InventoryItem", b =>
                {
                    b.HasOne("CoopGameServer.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoopGameServer.Domain.Rewards.RewardAudit", b =>
                {
                    b.HasOne("CoopGameServer.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoopGameServer.Domain.Wallets.PlayerWallet", b =>
                {
                    b.HasOne("CoopGameServer.Domain.Players.Player", null)
                        .WithOne()
                        .HasForeignKey("CoopGameServer.Domain.Wallets.PlayerWallet", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoopGameServer.Persistence.Matchmaking.MatchQueueMemberRecord", b =>
                {
                    b.HasOne("CoopGameServer.Persistence.Matchmaking.MatchQueueTicketRecord", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoopGameServer.Persistence.Parties.PartyMemberRecord", b =>
                {
                    b.HasOne("CoopGameServer.Persistence.Parties.PartyRecord", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoopGameServer.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
