// <auto-generated />
using System;
using CoopGameServer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoopGameServer.Api.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260806084933_AddRewardDataTables")]
    partial class AddRewardDataTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoopGameServer.Api.Domain.Inventories.InventoryItem", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlayerId", "ItemId");

                    b.ToTable("inventories", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventories_item_id_positive", "item_id > 0");

                            t.HasCheckConstraint("CK_inventories_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Api.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nickname");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("CoopGameServer.Api.Domain.Rewards.RewardAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_audit_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GoldAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_amount");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int?>("ItemQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("item_quantity");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("reward_audits", null, t =>
                        {
                            t.HasCheckConstraint("CK_reward_audits_gold_nonnegative", "gold_amount >= 0");

                            t.HasCheckConstraint("CK_reward_audits_has_reward", "gold_amount > 0 OR item_id IS NOT NULL");

                            t.HasCheckConstraint("CK_reward_audits_item_reward_shape", "(item_id IS NULL AND item_quantity IS NULL) OR (item_id IS NOT NULL AND item_quantity IS NOT NULL AND item_id > 0 AND item_quantity > 0)");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Api.Domain.Wallets.PlayerWallet", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlayerId");

                    b.ToTable("player_wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_player_wallets_gold_nonnegative", "gold >= 0");
                        });
                });

            modelBuilder.Entity("CoopGameServer.Api.Domain.Inventories.InventoryItem", b =>
                {
                    b.HasOne("CoopGameServer.Api.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoopGameServer.Api.Domain.Rewards.RewardAudit", b =>
                {
                    b.HasOne("CoopGameServer.Api.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoopGameServer.Api.Domain.Wallets.PlayerWallet", b =>
                {
                    b.HasOne("CoopGameServer.Api.Domain.Players.Player", null)
                        .WithOne()
                        .HasForeignKey("CoopGameServer.Api.Domain.Wallets.PlayerWallet", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
